### ISSUE TITLE
Visual C++ question

### ISSUE THREAD

**Issue by codykniffen** [datto/fireeye-red-team-countermeasure-scanner#2]
Is there a specific release of the Visual C++ redistributable that has to be installed? I have 32 and 64-bit versions of the following installed - 2005, 2008, 2010, 2012, 2013, and 2015-2019 and I'm still receiving the error that "The Visual C++ Redistributable is required in order to use YARA". 

If you could link to the required version, that'd be much appreciated.

**Comment by brking8910** [comment]
I   have found this error when I   dont run Powershell as admin and did not change to the directory before hand. Change your directory to where the script is located when in Powershell as admin and then execute the script.

**Comment by codykniffen** [comment]
Thanks. So yeah, was running as Admin but had to CD into that directory. It's running locally now. 
Would still like to know specifically which Visual C++ redist is required so we can script the check / install in our RMM tools.

**Comment by Datto-StanLee** [comment]
Hi Cody;
YARA's documentation is not stellar on this subject, but a document [here](https://pythonhosted.org/yara/howto/install.html) notes that the Visual C++ Redistributable 2010 is required.

**Comment by codykniffen** [comment]
Hm, yeah that is a bit irritating on their part, but I do appreciate the follow up. Thank you, sir!
